#!/bin/bash
echo 'Remember that you need to have right email and username here.'
git config --global -l
echo 'Otherwise do these first:'
echo 'git config --global user.email "you@example.com"'
echo 'git config --global user.name "username"'

read -p 'Write "ok", if you wish to continue, otherwise just press enter: ' answer

if (($answer == "ok")); then
	read -p 'App name: ' appname
	sudo npm install -g create-react-app
	create-react-app $appname
	cd $appname 
	npm install gh-pages --save-dev

	sed -i $'5i\  "homepage": "http://lightern.github.io/'${appname}$'_page",' ./package.json
	sed -i '15i\    "predeploy": "npm run build",' ./package.json
	sed -i '16i\    "deploy": "gh-pages -d build",' ./package.json

	git init
	git remote add origin $'https://github.com/lightern/'${appname}$'.git'

	npm run deploy
	
	git add .
	git commit -m "Create a React app and publish it to GitHub Pages"
	git push origin master
fi
